### Login
# @name login
POST http://localhost:3000/users/auth/login
Content-Type: application/json 

{
    "email": "maria@guess.com",
    "password": "guess"
}

###
@token = {{login.response.body.token}}

### Perfil
GET  http://localhost:3000/users/profile
Authorization: {{token}}


